### ISSUE TITLE
License missing from repo

### ISSUE THREAD

**Issue by karan** [jehugaleahsa/NRest#1]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by jehugaleahsa** [comment]
This project was literally just born yesterday. As with all my other
projects, there is no license. Do whatever you want with it. I will add my
usual licence section to the bottom of the readme for future reference.
