### ISSUE TITLE
Consider supporting URI Templates (RFC 6570) for constructing URIs

### ISSUE THREAD

**Issue by darrelmiller** [jehugaleahsa/NRest#2]
You might want to consider adding for the standard 6570 URI Templates.  There are a number of pre-existing .net libraries that support a ton of functionality for parameter replacement  (including one I wrote).  More details about its capabilities here:  http://www.bizcoder.com/constructing-urls-the-easy-way

Also, you may want to look at my [hapikit](http://hapikit.github.io/) stuff, it looks like we have similar goals, but taking a slightly different path.  We may be able to share some work.

**Comment by jehugaleahsa** [comment]
Thanks for the feedback. Dude, I love your UriTemplate functionality! I was
aware of some "standards" around the topic, but couldn't find anything
definitive.

At this point, I am just trying to make something better than RestSharp. I
had a lot of co-workers complaining about it, and knew I could slap
something together in just a few hours. Needless to say, I got a lot of
happy faces at work right now. I'm just slapping on "nice-to-haves" and
more unit tests.

I'll take a gander at your work. It does sound like we have the same goals.
I would guess you have more exposure to the wide variety of REST APIs and
the things SDK writers need.
